import { Lock, Hospital, Pill, TestTube, Activity, Bot, BarChart2, Moon } from 'lucide-react';
import RadialOrbitalTimeline from '../components/ui/radial-orbital-timeline';

const timelineData = [
  {
    id: 1,
    title: "Login & Register",
    date: "Auth",
    content: "Secure user authentication. Register with name, email, blood type and date of birth. Login to access your personal health data.",
    category: "Security",
    icon: Lock,
    relatedIds: [2, 3, 4, 5, 6],
    status: "completed",
    energy: 100,
  },
  {
    id: 2,
    title: "Doctor Visits",
    date: "CRUD",
    content: "Log every doctor visit with doctor name, specialty, date, notes and diagnosis. Edit or delete records anytime.",
    category: "Records",
    icon: Hospital,
    relatedIds: [1, 3, 4, 6],
    status: "completed",
    energy: 100,
  },
  {
    id: 3,
    title: "Medications",
    date: "CRUD",
    content: "Track all active medications with dosage and frequency. Set start and end dates. Mark as active or inactive.",
    category: "Tracking",
    icon: Pill,
    relatedIds: [1, 2, 6],
    status: "completed",
    energy: 100,
  },
  {
    id: 4,
    title: "Lab Results",
    date: "Analysis",
    content: "Record blood test results with normal ranges. Automatically flags HIGH or LOW values. Trend chart shows values over time.",
    category: "Analysis",
    icon: TestTube,
    relatedIds: [1, 2, 6, 7],
    status: "completed",
    energy: 95,
  },
  {
    id: 5,
    title: "Symptoms",
    date: "Tracking",
    content: "Log daily symptoms with severity slider 1 to 10. Track patterns over time to share with your doctor.",
    category: "Tracking",
    icon: Activity,
    relatedIds: [1, 6],
    status: "completed",
    energy: 85,
  },
  {
    id: 6,
    title: "AI Summary",
    date: "AI Powered",
    content: "Groq AI reads all your records and gives a plain English health summary. Flags concerns. No medical jargon. Powered by Llama 3.3.",
    category: "AI",
    icon: Bot,
    relatedIds: [2, 3, 4, 5],
    status: "completed",
    energy: 90,
  },
  {
    id: 7,
    title: "Lab Charts",
    date: "Visual",
    content: "Interactive Recharts line graph showing any lab value over time. Green and orange reference lines show normal range. Rising or falling trend analysis.",
    category: "Visual",
    icon: BarChart2,
    relatedIds: [4, 6],
    status: "completed",
    energy: 88,
  },
  {
    id: 8,
    title: "Dark Mode",
    date: "UI/UX",
    content: "Toggle between light and dark mode on the dashboard. Designed to be easy on the eyes for late night health checks.",
    category: "Design",
    icon: Moon,
    relatedIds: [1],
    status: "completed",
    energy: 75,
  },
];

export default function Timeline() {
  return <RadialOrbitalTimeline timelineData={timelineData} />;
}